.\" Process this file with
.\" groff -man -Tascii cryptday.1
.\"
.TH js_close 3 "August 2000" JS "js library reference"
.\" We don't want hyphenation (it's too ugly)
.\" We also disable justification when using nroff
.hy 0
.if n .na
.SH NAME
js_close \- Close a previously opened file
.SH SYNOPSIS
.nf
.B #include "JsStr.h"
.sp
.B "int js_close(js_file *desc)"
.fi
.SH DESCRIPTION
.B js_close
closes the file pointed to by
.B desc.
.SH "RETURN VALUE"
.B js_close
returns 
.I JS_SUCCESS 
on successful closing of the file,
.I JS_ERROR
otherwise.
.SH EXAMPLE
The following opens up the file "filename" for reading, then closes it:

.nf
	js_string *foo;
	js_file *bar;
	foo = js_create(256,1);		
	js_str2js(foo,"filename",8,1);
	js_open(foo,bar); 
	js_close(bar); 
.fi
.SH AUTHOR
Sam Trenholme <kiwi-zttfryb@koala.samiam.org>

