/* Put in the public domain 2000 by Sam Trenholme */

/* These are all of the labels in English for the ParseMaraRc.c program */

#define L_2ND_UNQUOTE "2nd quoted expression needs to be unquoted"
#define L_NEED_UNQUOTE "Quoted expression needs to be unquoted"
#define L_UNKNOWN_CHAR "Unknown character in line"
#define L_MAX4QUOTES "Maximum allowed quotes on a line is four"
#define L_VAR_NO_QUOTES "Variable name can not be in quotes"
#define L_LNEXT "Left square bracket must be immediately after variable name"
#define L_QUOTE_DICT "Dictionary element must be in quotes"
#define L_ONE_LEFT "Multiple left square brackets forbidden"
#define L_RAFTER_QUOTE "Right square bracket must be after quotes"
#define L_2ND_WORD "Second bare word found before quotes"
#define L_NEED_EQUAL "Statement needs an = sign"
#define L_CURLY_TOGETHER "{ must be immediately followed by }"
#define L_NO_HOH "Dictionary elements pointing to dictionaries unsupported"
#define L_NEED_VAL "Something must follow ="
#define L_NO_BACKSLASH "Backslash not supported yet"
#define L_VARNAME_EQUAL "Variable name needs an = sign"
#define L_EQUAL_BEFORE "Equals sign before variable name"
#define L_QUOTE_NO_EQUAL "Quoted string not preceeded by equals sign"
#define L_EQUAL_AFTER "Equals sign after variable value"
#define L_UNEXPECTED_CHAR "Unexpected character near end of line"
#define L_JSCREATE_FATAL "Fatal error creating js_string"
#define L_FILEMAKE_FATAL "Fatal error creating file"
#define L_JSBUFGETLINE_FATAL "Fatal error calling js_buf_getline"
#define L_PARSELINE_FATAL "Fatal error calling parseline"
#define L_KEYWORD2NUM_FATAL "Fatal error calling keyword2num"
#define L_DT_PMRC "Fatal error: "
#define L_DECLARED_TWICE " is declared more than once in mararc file.\nPlease remove or comment out this line:\n"
#define L_CANNOT_OPEN "Could not open mararc file at "
