#!/bin/bash

# Convert an ej document to a htmlpage document; which we then make a utf-8
# text document

TMP=$HOME/tmp
LINKS=$( which elinks )
LYNX=0
if [ -z "$LINKS" ] ; then
	LINKS=$( which links )
fi
if [ -z "$LINKS" ] ; then
	LINKS=$( which lynx )
	LYNX=1
fi

if which ej2html > /dev/null 2>&1 ; then
	CMD=ej2html
elif [ -e ../tools/ej/ej2html ] ; then
	CMD=../tools/ej/ej2html
elif [ -e ../../tools/ej/ej2html ] ; then
	CMD=../../tools/ej/ej2html
elif [ -e ../../../tools/ej/ej2html ] ; then
	CMD=../../../tools/ej/ej2html
elif [ -e ../../../../tools/ej/ej2html ] ; then
	CMD=../../../../tools/ej/ej2html
else
	echo Sorry\, can not find ej2html
	exit 1
fi

$CMD $1 > $TMP/$$.html
if [ "$LYNX" < 1 ] ; then
	$LINKS -dump-width 70 -dump -no-references -no-numbering $TMP/$$.html 
else
	lynx -dump -nolist $TMP/$$.html
fi
rm $TMP/$$.html

