# To use another CC, invoke as "make CC=clang" or some such
CC = gcc
# To use other flags, invoke as "make CFLAGS=-g -DCYGWIN" or some such
CFLAGS = -O3 -DCYGWIN -std=c99 -DNO_SPAWNER -DNO_LFS

all: coLunacyDNS 

clean: 
	rm -f *.o *.exe coLunacyDNS sipHash HalfSipHash1-3 HalfSipHash13 ; \
    cd lunacy ; make clean

lunacy/liblua.a:
	cd lunacy ; make CC="${CC}" CFLAGS="-std=c99 ${CFLAGS}" ; \
    cd tools/coLunacyDNS

coLunacyDNS.o: coLunacyDNS.c
	${CC} -std=c99 ${CFLAGS} -DCYGWIN -c -Wall -o coLunacyDNS.o coLunacyDNS.c 	

coLunacyDNS: coLunacyDNS.o lunacy/liblua.a
	${CC} -std=c99 ${CFLAGS} -Wall -o coLunacyDNS coLunacyDNS.o \
    lunacy/liblua.a -lm

HalfSipHash13.o: HalfSipHash13.c 
	${CC} -std=c99 ${CFLAGS} -c -Wall -o  HalfSipHash13.o HalfSipHash13.c

HalfSipHash13: HalfSipHash13.o lunacy/liblua.a
	${CC} -std=c99 ${CFLAGS} -Wall -o HalfSipHash13 HalfSipHash13.o \
    lunacy/liblua.a -lm
