#define L_WARNING "Предупреждение: "
#define L_ONLINE " в строке "
#define L_F "\n"
#define L_INITCSV " хеш csv1 инициализирован неправильно.\nУбедитесь, что csv1 инициализирован с помощью csv1 = {}"
#define L_BADZONE "Файл зоны имеет неправильное имя. Все файлы зоны должны заканчиваться точкой, например,\ncsv1[\"example.com.\"] = \"filename\".\nВ этой строке mararc указывает на проблему: "
#define L_ZONEOPEN "Невозможно открыть файл зоны для зоны "
#define L_FATAL "Неустранимая ошибка в файле зоны "
#define L_ABOUT_THIS " (прерывание этого файла зоны)"
#define L_S_ZONE "Синтаксическая ошибка в файле зоны "
#define L_L " ("
#define L_R ")"
#define L_FIRST_SOA "Первая запись в файле зоны csv1 должна быть записью SOA."
#define L_ZONE "Зона: "
#define L_SECOND_SOA "Вторичный SOA в файле зоны "
#define L_ABORT " ((прерывание файла зоны)"
#define L_DDIP_WARN "Если задать десятичную запись IP-адреса для записей NS, CNAME и MX, то у некоторых DNS-серверов будет ошибка получения ответа"
#define L_LINE_NUMBER "Номер строки "
#define L_TOO_LONG " слишком длинный файл "
