#define L_WARNING "Aviso: "
#define L_ONLINE " on line "
#define L_F "\n"
#define L_INITCSV "csv1 hash no est corretamente inicializado.\nTenha certeza que csv1 esteja inicializado com csv1 = {}"
#define L_BADZONE "O arquivo de zona est nomeado incorretamente.  Todos os arquivos de zona devem terminar com um ponto, e.g.\ncsv1[\"exemplo.com.\"] = \"nomedoarquivo\".\nAqui est a linha com problemas no mararc: "
#define L_ZONEOPEN "No se pode abrir o arquivo de zona para a zona "
#define L_FATAL "Erro fatal no arquivo de zona "
#define L_ABOUT_THIS " (abortando este arquivo de zona)"
#define L_S_ZONE "Erro de sintxe no arquivo arquivo de zona "
#define L_L " ("
#define L_R ")"
#define L_FIRST_SOA "O primeiro registro em um arquivo de zona csv1 deve ser um registro SOA."
#define L_ZONE "Zona: "
#define L_SECOND_SOA "Segundo SOA em arquivo zona"
#define L_ABORT " (abortando arquivo de zona)"
#define L_DDIP_WARN "IP decimal para NS, CNAME, ou MX no funciona em alguns servidores de DNS"
#define L_LINE_NUMBER "Nmero da linha"
#define L_TOO_LONG " longo demais no arquivo."

