#define L_WARNING "Warning: "
#define L_ONLINE " on line "
#define L_F "\n"
#define L_INITCSV "csv1 hash is not correctly initialized.\nMake sure to have csv1 initialized with csv1 = {}"
#define L_BADZONE "A zone file is incorrectly named.  All zone files must end with a dot, e.g.\ncsv1[\"example.com.\"] = \"filename\".\nHere is the line in the mararc with the problem: "
#define L_ZONEOPEN "Can not open zone file for zone "
#define L_FATAL "Fatal error in zone file "
#define L_ABOUT_THIS " (aborting this zone file)"
#define L_S_ZONE "Syntax error in zone file "
#define L_L " ("
#define L_R ")"
#define L_FIRST_SOA "First record in csv1 zone file must be SOA record."
#define L_ZONE "Zone: "
#define L_SECOND_SOA "Second SOA in zone file "
#define L_ABORT " (aborting zone file)"
#define L_DDIP_WARN "Dotted decimal IP for NS, CNAME, or MX does not work with some DNS servers"
#define L_LINE_NUMBER "Line number "
#define L_TOO_LONG " is too long in file "
