#define L_LOG " Log: "
#define L_N "\n"
#define L_FATAL "Erro fatal: "
#define L_ACL_LIST_RECURSE "No foi possvel fazer a lista de IP ACL para consultas recursivas."
#define L_INIT_SPAMMERS "No foi possvel fazer a lista de spammers"
#define L_RANDOM_IF_RECURSE "Arquivo random_seed_file deve ser configurado se o DNS recursivo estiver habilitado"
#define L_INVALID_CACHESIZE "A varivel maximum_cache_size tem um valor invlido. Revertendo para valor padro."
#define L_BIND2ADDR "Conectando ao endereo"
#define L_CAUGHT_PIPE "Caught SIGPIPE"
#define L_CAUGHT_SIG "Caught Signal"
#define L_BAD_QUERY "Consulta incorreta recebida: "
#define L_SYSERROR "Sistema dito "
#define L_MLC "No foi possvel criar a string mararc_loc"
#define L_MLL "No foi possvel setar localizao para a string mararc_loc"
#define L_EC "No foi possvel criar a string errors"
#define L_EL "No foi possvel setar localizao para a string errors"
#define L_UC "No foi possvel criar a string uidstr"
#define L_UL "No foi possvel setar localizao para a string uidstr"
#define L_VC "No foi possvel criar a string verbstr"
#define L_VL "No foi possvel setar localizao para a string verbstr"
#define L_MC "No foi possvel criar a string maxpstr"
#define L_ML "No foi possvel setar localizao para a string maxpstr"
#define L_CC "No foi possvel criar a string chrootn"
#define L_CL "No foi possvel setar localizao para a string chrootn"
#define L_KQC "No foi possvel criar a string kvar_query"
#define L_KQL "No foi possvel setar localizao para a string kvar_query"
#define L_BAC "No foi possvel criar a string bins_address"
#define L_BAL "No foi possvel setar localizao para a string bind_address"
#define L_IC "No foi possvel criar a string incoming"
#define L_IL "No foi possvel setar localizao para a string incoming"
#define L_UCC "No foi possvel criar a string uncomp"
#define L_UCL "No foi possvel setar localizao para a string uncomp"
#define L_LOC_MARARC "Erro em localizar o arquivo mararc"
#define L_MARARC_ARG "No foi possvel obter mararc da linha de comando"
#define L_USAGE "Uso: mararc [-f mararc_location]"
#define L_MARARC_PARSE "Erro na anlise do contedo do arquivo mararc"
#define L_MARARC_LINE "Erro na anlise do contedo do arquivo mararc na linha "
#define L_ERROR_CODE "Cdigo de erro: "
#define L_KVAR_Q "No foi possvel criar kvar_query"
#define L_MAXPROC "Problema em obter o valor maxprocs.\nmaxprocs deve ser setado antes de iniciar o servidor MaraDNS"
#define L_MAXPROC_NUM "Problema na converso de maxprocs para nmero\nDeve ser um nmero diferente de zero"
#define L_MAXPROC_SET "Incapaz de ajustar o nmero mximo dos processos"
#define L_MAXPROC_MAX "maxprocs no pode ser maioir que 500\nConfigurando maxprocs para 500"
#define L_CHROOT_KVAR "Erro em conseguir chroot kvar.\nVoc deve ter chroot_dir setado se quiser iniciar como root"
#define L_CHROOT_NT "Erro em fazer chroot para a string nt.\nVerifique se o diretrio chroot tem no mximo 200 caractres"
#define L_CHROOT_CHANGE "Problema em mudar para o diretrio root.\nTenha certeza que chroot_dir aponta para um diretrio vlido"
#define L_CHROOT_DO "Problema em mudar para o diretrio root."
#define L_CHROOT_SUCCESS "Diretrio root mudado"
#define L_NOBIND "Problema em obter chroot kvar.\nVoc deve ter bind_address setado para o IP que maradns ir escutar"
#define L_BINDFAIL "Problema em binding para porta 53.\n"
#define L_BIND_SUCCESS "Socket aberto na porta UDP 53"
#define L_NOUID "Problema em obter maradns_uid kvar.\nVoc deve ter maradns_uid setada se voc comeou isto como root"
#define L_BADUID "maradns_uid  menor que 10 ou no  nmero.\nEste uid deve ter um valor igual ou maior que 10"
#define L_NODROP "No foi possivel finalizar uid root"
#define L_STILL_ROOT "Ainda parecemos ser root"
#define L_DROP_SUCCESS "Root privilgios finalizados"
#define L_BEROOT "Problema em binding para porta 53.\nVoc deve root para executar isto."
#define L_NOBIGHASH "No foi possvel criar um grande hash"
#define L_NOPOPULATE "Erro ao rodar o programa populate_main. Favor leia o MaraDNS FAQ"
#define L_POPULATE_FATAL "Este erro na populao do hash  fatal"
#define L_RRS_LOADED "Todas RRs foram carregadas"
#define L_DATAWAIT "Esperando dados na porta 53"
#define L_GOTDATA "Menssagem recebida, processando"
#define L_INITCACHE_FAIL "Init_cache() falhou. Se voc estiver vendo isso, ento  um bug.\nFavor leia o MaraDNS FAQ"
#define L_ERROR_VALUE "Erro de valor (para desenvolvedores de software): "
#define L_INITCRYPTO_FAIL "Init_crypto() falhou. Se voc estiver vendo isso, ento  um bug.\nFavor leia o MaraDNS FAQ"
#define L_OPENSEED_FAIL "No foi possvel abrir random_seed_file"
#define L_NEED16BYTES "O random_seed_file precisa ser 16 bytes ou maior"
#define L_THISIS "Est  a verso do MaraDNS"
#define L_COMPILED "Compilado em um"
#define L_RTFM "Para informao de uso, 'man maradns'"
#define L_SETROOTNS "root_servers[\".\"] ou upstream_servers[\".\"] devem ser configurado em \nmararc\ne.g. root_servers[\".\"] = \"198.41.0.4\"\nEm adio, root_servers = {} (ou upstream_servers = {}) deve ser precedido com est\nlinha"
#define L_BADROOTNS "root_servers[\".\"] (ou upstream_servers) no arquivo mararc \n invlido.\nExemplo de um valor correto: root_servers[\".\"] = \"198.41.0.4\""
#define L_CHOOSEONE "Ambos root_servers e upstream_servers esto configurados no arquivo mararc \nFavor escolher um ou outro; ambos no podem estar ativo ao mesmo tempo."
#define L_INVALID_MAXGLUE "max_glueless_level precisa ser um nmero maior que zero"
#define L_INVALID_MAXQTOTAL "max_queries_total precisa ser um nmero maior que zero"
#define L_INVALID_TIMEOUT "timeout_seconds precisa ser um nmero maior que zero"
#define L_TIMESTAMP "Timestamp: "
#define L_COMPRESS_ERROR "Erro de compreso: "
