#define L_WARNING "Warnung: "
#define L_ONLINE " in Zeile "
#define L_F "\n"
#define L_INITCSV "csv1 hash ist nicht korrekt initialisiert.\nStellen Sie sicher, dass csv1 mit cvs1 = {} initalisiert wurde."
#define L_BADZONE "Eine Zonen Datei ist falsch bezeichnet. Alle Zonen Dateien muessen mit einem Punkt enden, bspw.\ncsv1[\"example.com.\"] =\"Dateiname\".\nHier ist die Zeile aus mararc die das Problem beinhaltet: "
#define L_ZONEOPEN "Kann fuer folgende Zone die Zonen Datei nicht oeffnen "
#define L_FATAL "Fataler Fehler in Zonen Datei "
#define L_ABOUT_THIS " (Breche in dieser Zonen Datei ab)"
#define L_S_ZONE "Syntax eFehler in Zonen Datei "
#define L_L " ("
#define L_R ")"
#define L_FIRST_SOA "Erste Eintrag in csv1 Zonen Date muss ein SOA Eintrag sein."
#define L_ZONE "Zone: "
#define L_SECOND_SOA "Zweiter SOA in Zonen Datei "
#define L_ABORT " (breche Zonen Datei ab)"
#define L_DDIP_WARN "Punktierte dezimale IP fuer NS, CNAME oder MX funktioniert nicht mit einigen DNS Servern"
#define L_LINE_NUMBER "Zeilen Nummer "
#define L_TOO_LONG " ist zu lang in Datei "

