#define L_FATAL_COMMENT "# Erro fatal: "
#define L_TIMEOUT "Tempo de espera esgotado"
#define L_USAGE "Uso: getzone zone_name zone_server_IP"
#define L_USAGE_FETCH "Uso: fetchzone zone_name zone_server_IP"
#define L_VALID_IP "Use um IP vlido para o servidor de zonas, por favor"
#define L_NO_SOCK "Impossvel criar socket TCP"
#define L_NO_CONNECT "Impossvel conectar com o servidor de zonas"
#define L_NO_SEND "Impossvel criar o objeto para enviar"
#define L_NO_HEADER "Impossvel criar o cabealho DNS"
#define L_NO_ZSTRING "Impossvel criar o objeto para a zona"
#define L_QSTR2JS_ERROR "qstr2js"
#define L_APPEND_Z "Impossvel adicionar a cadeia de zona a um objeto da zona"
#define L_APPEND_D "Impossvel adicionar o ponto final na cadeia da zona"
#define L_INVALID_NAME "Nome de zona invlido"
#define L_APPEND_ZS "Impossvel adicionar a cadeia da zona para ser envida"
#define L_ADD_QT "No se pode adicionar o tipo de consulta  ser enviada"
#define L_ADD_QC "No se pode adicionar a clase de consulta  ser enviada"
#define L_SEND_2BYTE "No se pode enviar o cabealho de 2 bytes ao servidor de zonas"
#define L_SEND_QUERY "No se pode enviar a consulta ao servidor de zonas"
#define L_C_RRNAME "Impossvel de criar rr.name"
#define L_MNAME "Impossvel de criar soa.mname"
#define L_RNAME "Impossvel de criar soa.rname"
#define L_NOT_MANLY "A resposta do servidor no  grande o suficiente para o cabealho"
#define L_NO_GET "No h memria para a cadeia"
#define L_NO_EXPAND "No pode alocar memria para cadeia expandida"
#define L_SERVER "No pode obter pacote do servidor"
#define L_DECOMPRESS "Erro fatal executando a decompresso"
#define L_RHEADER "No se pode ler o cabealho do servidor"
#define L_FORMAT "Erro de formato"
#define L_SERVER_FAIL "Falha do servidor"
#define L_NAME "Erro em nome"
#define L_NOTIMPL "No implementado"
#define L_REFUSE "Recusado"
#define L_RCODE "Rcode > 5"
#define L_DLABEL "dlabel no vlido em questo"
#define L_READ_RR_H "Erro fatal executando read_rr_h"
#define L_GET_S "No se pode obter a cadeia"
#define L_GET_COPY "Erro fatal copiando o nome a get"
#define L_BALIWICK "# Incapacitado out-of-baliwick do seguintes registros "
#define L_HASH "# "
#define L_CGET "No se pode fazer get string"
#define L_RDDATA "Problema em obter rddata"
#define L_TRANS "Problema em traduzir o nome do registro A"
#define LF "\n"
#define L_HNAME "Problema Hname "
#define L_ZERO "No se admite nomes de comprimento 0!"
