#define L_FATAL_COMMENT "# Критическая ошибка: "
#define L_TIMEOUT "Время ожидания истекло."
#define L_USAGE "Использование: getzone zone_name zone_server_IP"
#define L_USAGE_FETCH "Использование: fetchzone zone_name zone_server_IP"
#define L_VALID_IP "Пожалуйста, используйте действительный IP для сервера зоны."
#define L_NO_SOCK "Невозможно создать сокет TCP."
#define L_NO_CONNECT "Невозможно подключиться к серверу зоны."
#define L_NO_SEND "Невозможно создать объект строки отправки."
#define L_NO_HEADER "Невозможно создать заголовок DNS."
#define L_NO_ZSTRING "Невозможно создать строковый объект зоны."
#define L_QSTR2JS_ERROR "qstr2js"
#define L_APPEND_Z "Невозможно добавить строку зоны в объект зоны."
#define L_APPEND_D "Невозможно добавить точку в конце строкового объекта зоны."
#define L_INVALID_NAME "Неверная форма имени зоны."
#define L_APPEND_ZS "Невозможно добавить строку зоны для отправки строки."
#define L_ADD_QT "Не удалось добавить тип запроса для отправки."
#define L_ADD_QC "е удалось добавить класс запроса для отправки."
#define L_SEND_2BYTE "Не удалось отправить 2-байтовый заголовок на сервер зоны."
#define L_SEND_QUERY "Не удалось отправить запрос на сервер зоны"
#define L_C_RRNAME "Не удалось создать rr.name"
#define L_MNAME "Не удалось создать soa.mname"
#define L_RNAME "Не удалось создать soa.rname"
#define L_NOT_MANLY "Ответ от сервера недостаточно длинный для удержания заголовка."
#define L_NO_GET "Не удалось выделить память для получения строки."
#define L_NO_EXPAND "Не удалось выделить память для раскрываемой строки."
#define L_SERVER "Не удалось получить пакет с сервера."
#define L_DECOMPRESS "Неустранимая ошибка выполнения декомпрессии."
#define L_RHEADER "Не удалось прочитать заголовок с сервера."
#define L_FORMAT "Ошибка формата."
#define L_SERVER_FAIL "Ошибка сервера."
#define L_NAME "Ошибка имени."
#define L_NOTIMPL "Не реализовано."
#define L_REFUSE "Отказано."
#define L_RCODE "Rcode > 5"
#define L_DLABEL "Недопустимая метка в вопросе"
#define L_READ_RR_H "Неустранимая ошибка при выполнении read_rr_h."
#define L_GET_S "Невозможно получить строку"
#define L_GET_COPY "Неустранимая ошибка копирования имени для получения"
#define L_BALIWICK "# После этого знака запись отключена из-под контроля."
#define L_HASH "# "
#define L_CGET "Не удается получить строку"
#define L_RDDATA "Проблема с получением rddata"
#define L_TRANS "Проблема с переводом имени A-записи"
#define LF "\n"
#define L_HNAME "Проблема с именем"
#define L_ZERO "Нет имён 0-й длины!"
