#define L_LOG "Log: "
#define L_FATAL "Erro fatal: "
#define L_MLC "No pode criar a string mararc_loc"
#define L_MLL "No pode setar locale para a string mararc_loc"
#define L_EC "No pode criar a string de erros"
#define L_EL "No pode setar locale para a string de erros"
#define L_KSC "No pode criar a string kvar_str"
#define L_KSL "No pode setar locale para a string kvar_str"
#define L_VC "No pode criar a string verbstr"
#define L_VL "No pode setar locale para a string verbstr"
#define L_MC "No pode criar a  string maxpstr"
#define L_ML "No pode setar locale para string maxpstr"
#define L_CC "No pode criar a string chrootn"
#define L_CL "No pode setar locale para a string chrootn"
#define L_KQC "No pode criar a string kvar_query"
#define L_KQL "No pode setar locale para a string kvar_query"
#define L_BAC "No pode criar a string bins_address"
#define L_BAL "No pode setar locale para a string bind_address"
#define L_IC "No pode criar a string incoming"
#define L_IL "No pode setar locale para a string incoming"
#define L_UC "No pode criar a string uncomp"
#define L_UL "No pode setar locale para a string uncomp"
#define L_MW "Erro em localizar o arquivo mararc"
#define L_GET_MARARC "No foi possvel adquirir mararc da linha de comando"
#define L_USAGE "Uso: zoneserver [-f mararc_location]"
#define L_PARSE_MARARC "Erro ao analizar o contedo do arquivo mararc"
#define L_PARSE_MARARC_LINE "Erro ao analizar o contedo do arquivo mararc na linha"
#define L_ERROR_CODE "Cdigo do Erro: "
#define LF "\n"
#define L_MAKE_KQ "No pode criar kvar_query"
#define L_MAXPROCS "O problema em obter o valor de maxprocs.\nmaxprocs deve ser ajustado antes de iniciar o servidor MaraDNS "
#define L_MAXPROCS_NUM "Problema na converso do maxprocs para um nmero\nEste deve ser um nmero no zero"
#define L_SETMAX "Incapaz de ajustar o nmero mximo de processos "
#define L_CHROOT "Problema em obter chroot kvar.\nVoc deve ter configurado chroot_dir se inicializa com root"
#define L_CHROOT_NT "Problema em fazer chroot nt string.\nCertifique-se que o diretrio chroot tem 200 characteres ou menos "
#define L_NO_CHROOT "Problema em mudar para o diretrio chroot.\nCertifique-se que chroot_dir aponta para um diretrio vlido"
#define L_CHROOT_ERROR "Problema em mudar para o diretrio root."
#define L_CHROOT_SUCCESS "Diretrio root mudado"
#define L_BIND_GET "Problema em conseguir chroot kvar.\nVoc deve ter o bind_address ajustados ao IP do zoneserver que escutar."
#define L_BIND "Problema na port 53.\nMuito provvel, um outro processo j est escutando na porta 53"
#define L_SOCKET_SUCCESS "Socket aberto na porta 53 TCP"
#define L_NO_UID "Problema em conseguir maradns_uid kvar.\nVoc deve ter maradns_uid ajustado se inicializado como root"
#define L_UID_INVALID "maradns_uid  menor que 10 ou no  um nmero.\nEste uid deve ter um valor igual ou maior que 10"
#define L_NODROP "No pode drop root uid"
#define L_STILL_ROOT "Ns parecemos ainda ser root"
#define L_DROP_SUCCESS "Privilgios root perdidos"
#define L_BE_ROOT "Problema em conectar na porta 53.\nVoc deveria executar isto como root"
#define L_NO_ACL "No pode ler dados de zone_transfer_acl"
#define L_ACL_INETD "zone_transfer_acl no deve ser ajustada quando executada em modo inetd"
#define L_ACL_LIST "No pode fazer a lista de ip ACL\nFavor adicionar tcp_convert_acl com tcp_convert_server e/ou zone_transfer_acl\npara o arquivo mararc. Veja o man page mararc para mais detalhes"
#define L_WAITING "Aguardando dados na porta 53"
#define L_GOT "Menssagem recebida, processando"
#define L_NO_ZONE_HERE "Zona que ns no pedimos, desconectando "
#define L_THISIS "Est  a verso do zoneserver do MaraDNS"
#define L_RTFM "Para informaes de uso, 'man zoneserver'"
